language: c
sudo: required
env:
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07

install:
  - curl -sSL https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh | bash -ex
  - ocamlc -v

before_script: make
script: make test
