language: c
sudo: required
env:
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07

install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
  - bash -ex .travis-ocaml.sh

before_script: make
script: make test
